// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type Mutation struct {
}

type NewUser struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Name     string `json:"name"`
}

type Query struct {
}

type UserOps struct {
	Register string         `json:"register"`
	Login    *LoginResponse `json:"login"`
}

type UserQuery struct {
	Me *User `json:"me"`
}
